from django.db import models

# Create your models here.
class data(models.Model):
    project_idx = models.IntegerField()
    job_number = models.CharField(max_length=50)
    project_name = models.CharField(max_length=100)
    client = models.CharField(max_length=100)
    cdivision = models.CharField(max_length=100)
    research_type = models.CharField(max_length=100)
    team = models.CharField(max_length=100)
    prod_type = models.CharField(max_length=100)
    prod_business = models.CharField(max_length=100)
    prod_target = models.CharField(max_length=100)
    industry = models.CharField(max_length=100)
    prod_cat1 = models.CharField(max_length=100)
    prod_cat2 = models.CharField(max_length=100)
    prod_cat3 = models.CharField(max_length=100)
    brand = models.CharField(max_length=100)
    date = models.CharField(max_length=100)
    country = models.CharField(max_length=100)
    dc_type = models.CharField(max_length=100)
    test_type = models.CharField(max_length=100)
    sample_composition = models.CharField(max_length=100)
    sampe_type = models.CharField(max_length=100)
    gender = models.CharField(max_length=100)
    sample_number = models.CharField(max_length=50)
    concept_idx = models.CharField(max_length=50)
    s_board = models.CharField(max_length=50)
    s_video = models.CharField(max_length=50)
    s_proto = models.CharField(max_length=50)
    s_working = models.CharField(max_length=50)
    s_final = models.CharField(max_length=50)
    s_branded = models.CharField(max_length=50)
    s_priced = models.CharField(max_length=50)
    currency = models.CharField(max_length=50)
    price = models.CharField(max_length=50)
    price_min = models.CharField(max_length=50)
    price_max = models.CharField(max_length=50)
    price_usd = models.CharField(max_length=50)
    market_launch = models.CharField(max_length=50)
    maket_size = models.CharField(max_length=50)
    market_sales = models.CharField(max_length=50)
    market_share = models.CharField(max_length=50)
    index = models.CharField(max_length=50)
    scale = models.CharField(max_length=50)
    tb = models.CharField(max_length=50)
    t2b = models.CharField(max_length=50)
    sd = models.CharField(max_length=50)
    mean = models.CharField(max_length=50)

